<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:set var="pageTitle" value="Padres" scope="request" />
<%@ include file="/WEB-INF/includes/head.jspf" %>
<body class="parent-portal" data-user-level="${sessionScope.user.level}" data-specialty="general" data-specialty-source="parent-portal">
<c:set var="navbarHomeUrl" value="${pageContext.request.contextPath}/padre" />
<c:set var="manualHrefOverride" value="${pageContext.request.contextPath}/pdfs/manual-padres.pdf" />
<%@ include file="/WEB-INF/includes/navbar.jspf" %>
<main><section class="container page-shell">
  <div class="info-bar"><span>Bienvenido/a ${sessionScope.user.fullName}</span></div>
  <div class="top-section planilla-hero hero-shell parent-hero" data-specialty="${multipleHijos ? 'general' : selectedEspecialidad}"><div class="planilla-hero__header"><div class="planilla-hero__info"><span class="badge"><span class="dot"></span>Padres</span><h1>Notas de mis hijos</h1><p class="planilla-subtitle">Consultá el rendimiento y las tareas de cada alumno.</p></div></div></div>
  <c:if test="${empty hijos}"><div class="empty-state empty-state-card">No hay hijos asociados a este usuario padre.</div></c:if>
  <c:if test="${not empty hijos}">
    <c:if test="${multipleHijos}"><section class="parent-child-selector" aria-label="Seleccionar alumno"><div class="parent-child-selector__heading"><h2>Mis hijos</h2></div><div class="parent-child-grid"><c:forEach var="hijo" items="${hijos}"><c:url var="childUrl" value="/padre"><c:param name="alumnoId" value="${hijo.id}" /></c:url><a class="parent-child-card ${hijo.id == selectedAlumnoId ? 'is-active' : ''}" href="${childUrl}" data-specialty="${hijo.especialidadNombre}"><span class="parent-child-card__accent"></span><span class="parent-child-card__content"><span class="parent-child-card__specialty"><span class="parent-specialty-dot"></span><c:out value="${hijo.especialidadNombre}" /></span><span class="parent-child-card__name"><c:out value="${hijo.nombre}" /> <c:out value="${hijo.apellido}" /></span><span class="parent-child-card__average">Promedio general: <strong><c:out value="${promedioPorAlumno[hijo.id]}" />%</strong></span></span></a></c:forEach></div></section></c:if>
    <section class="section-block card parent-summary-card" data-specialty="${selectedEspecialidad}"><div class="parent-summary-card__heading"><div class="section-heading">Materias de <c:forEach var="hijo" items="${hijos}"><c:if test="${hijo.id == selectedAlumnoId}"><c:out value="${hijo.nombre}" /></c:if></c:forEach></div></div>
      <c:choose><c:when test="${not empty selectedSummary}"><div class="parent-subject-list"><c:forEach var="item" items="${selectedSummary}"><details class="parent-subject-accordion" ${item.planillaId == selectedPlanillaId ? 'open' : ''}><summary><span class="parent-subject-accordion__title"><strong><c:out value="${item.materiaNombre}" /></strong></span><span class="parent-subject-accordion__metric"><small>Tareas</small><strong><c:out value="${item.tareasCount}" /></strong></span><span class="parent-subject-accordion__metric"><small>Puntos</small><strong><c:out value="${item.puntos}" /> / <c:out value="${item.totalPosible}" /></strong></span><span class="parent-subject-accordion__metric"><small>Nota</small><strong><c:out value="${item.nota}" /></strong></span><span class="parent-subject-accordion__metric"><small>Porcentaje</small><strong><c:out value="${item.porcentaje}" />%</strong></span></summary><c:choose><c:when test="${not empty tareasPorPlanilla[item.planillaId]}"><div class="parent-task-table-wrap"><table class="grade-table parent-task-table"><thead><tr><th>Tarea</th><th>Fecha</th><th>Puntos</th></tr></thead><tbody><c:forEach var="grade" items="${tareasPorPlanilla[item.planillaId]}"><tr><td><c:out value="${grade.tareaTitulo}" /></td><td><c:out value="${grade.fecha}" /></td><td><strong><c:out value="${grade.puntos}" /> / <c:out value="${grade.total}" /></strong></td></tr></c:forEach></tbody></table></div></c:when><c:otherwise><div class="parent-task-empty">Esta materia todavía no tiene tareas cargadas.</div></c:otherwise></c:choose></details></c:forEach></div></c:when><c:otherwise><div class="empty-state">No hay materias con tareas cargadas para este alumno.</div></c:otherwise></c:choose>
    </section>
  </c:if>
</section><footer class="footer"><hr><p>Colegio Técnico Nacional</p><p><a href="${pageContext.request.contextPath}/privacidad">Política de privacidad</a> | <a href="${pageContext.request.contextPath}/terminos">Términos de servicio</a></p></footer></main>
<%@ include file="/WEB-INF/includes/footer-scripts.jspf" %>
</body></html>
