import { useEffect, useRef, useState } from 'react';
import { ActivityItem, Badge, Button, Card, DesignSystem, EmptyState, Icon, Skeleton, TopNav, specialties, tokens } from '..';
import './gallery.css';

/** Executable usage examples. Demo data only; no network, auth or persistence. */
export function Gallery() {
  const [specialty, setSpecialty] = useState('informatica');
  const [customAccent, setCustomAccent] = useState('#7a1f2b');
  const [custom, setCustom] = useState(false);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  useEffect(() => () => clearTimeout(timer.current), []);
  const notice = (text: string) => setMessage(text);
  const save = () => {
    setSaving(true); setMessage('');
    timer.current = setTimeout(() => { setSaving(false); setMessage('Ejemplo completado. No se guardaron datos reales.'); }, 1500);
  };
  return <DesignSystem specialty={specialty} accent={custom ? customAccent : undefined} className="ds-gallery">
    <a className="ds-skip" href="#muestra">Saltar a los componentes</a>
    <div className="ds-gallery-wrap">
      <header className="ds-gallery-intro"><div><p className="ds-eyebrow">CTN · CARPETA ACADÉMICA</p><h1 className="ds-display">Una base común.<br /><span className="ds-accent">Cada especialidad, su identidad.</span></h1><p className="ds-secondary">Sistema de diseño / Fase 01 · Propuesta para revisión</p></div><Badge tone="brand">Biblioteca de componentes</Badge></header>
      <aside className="ds-demo-controls" aria-label="Configuración de la muestra"><div><label htmlFor="ds-specialty">Especialidad</label><select id="ds-specialty" value={specialty} onChange={(event) => setSpecialty(event.target.value)}>{Object.entries(specialties).map(([key, entry]) => <option key={key} value={key}>{entry.label}</option>)}</select></div><label className="ds-custom-toggle"><input type="checkbox" checked={custom} onChange={(event) => setCustom(event.target.checked)} />Probar otro acento</label><label className="ds-color-label" htmlFor="ds-accent">Color personalizado<input id="ds-accent" type="color" value={customAccent} disabled={!custom} onChange={(event) => setCustomAccent(event.target.value)} /></label><p className="ds-tertiary ds-small">El cambio se aplica a toda esta muestra.<br />Las pantallas del sistema permanecen intactas.</p></aside>
      <main id="muestra" className="ds-gallery-main" tabIndex={-1}>
        <section className="ds-stack" aria-labelledby="nav-title"><div className="ds-section-title"><span>01</span><h2 id="nav-title" className="ds-h2">Navegación e identidad</h2></div><TopNav brand="Carpeta Académica" subtitle="Colegio Técnico Nacional de Asunción" logo={<Icon name="book" />} items={[{ id: 'inicio', label: 'Inicio', href: '#muestra' }, { id: 'cursos', label: 'Cursos', href: '#cards' }, { id: 'catedra', label: 'Libro de cátedra', href: '#activity' }, { id: 'planillas', label: 'Planillas', href: '#states' }]} activeId="inicio" user={{ name: 'María González', role: `Docente · ${specialties[specialty as keyof typeof specialties].label}`, initials: 'MG', href: '#profile-example' }} /></section>
        <section id="cards" className="ds-stack" aria-labelledby="cards-title"><div className="ds-section-title"><span>02</span><h2 id="cards-title" className="ds-h2">Contenedores con jerarquía</h2></div><div className="ds-demo-grid"><Card title="Prepará tu próxima clase" description="Destacada · acción principal de una sección" variant="featured" action={<Badge tone="brand">Tu especialidad</Badge>}><div className="ds-stack"><p className="ds-secondary">Un punto de partida claro para el contenido, la asistencia y los recursos de cada encuentro.</p><div><Button aria-label="Preparar clase de ejemplo" icon={<Icon name="plus" />} onClick={() => notice('Preparar clase: ejemplo visual, sin abrir una clase real.')}>Preparar clase</Button></div></div></Card><Card title="El trabajo, en contexto" description="Estándar · información complementaria"><div className="ds-stack"><p className="ds-secondary">Superficies discretas, títulos legibles y espacio para que el contenido respire.</p><div className="ds-row"><Badge tone="neutral">Segundo curso</Badge><Badge tone="success">Al día</Badge></div></div></Card></div><div className="ds-demo-surfaces">{([1,2,3] as const).map((level) => <Card key={level} level={level} title={`Superficie ${level}`} headingLevel={3}><p className="ds-secondary ds-small">{level === 1 ? 'Secciones principales' : level === 2 ? 'Contenido dentro de una sección' : 'Contenido elevado y controles'}</p><p className="ds-tertiary ds-caption">Texto terciario con contraste AA</p></Card>)}</div></section>
        <section className="ds-stack" aria-labelledby="controls-title"><div className="ds-section-title"><span>03</span><h2 id="controls-title" className="ds-h2">Acciones y estados</h2></div><div className="ds-demo-grid"><Card title="Botones" description="Hover, foco, deshabilitado y carga"><div className="ds-stack"><div className="ds-row"><Button aria-label="Guardar ejemplo" loading={saving} loadingLabel="Guardando" onClick={save} icon={<Icon name="check" />}>{saving ? 'Guardando…' : 'Guardar ejemplo'}</Button><Button variant="secondary" aria-label="Cancelar ejemplo" onClick={() => { clearTimeout(timer.current); setSaving(false); notice('Ejemplo cancelado.'); }}>Cancelar</Button><Button variant="icon" aria-label="Ver notificaciones de ejemplo" icon={<Icon name="bell" />} onClick={() => notice('No hay notificaciones nuevas en esta muestra.')} /></div><div className="ds-row"><Button aria-label="Acción no disponible" disabled>No disponible</Button><Button variant="secondary" aria-label="Guardar cambios" loading loadingLabel="Guardando">Guardando…</Button></div><p className="ds-tertiary ds-small">Usá Tab para revisar el foco visible y Enter o Espacio para activar un botón.</p></div></Card><Card title="Etiquetas" description="La marca identifica; el estado informa"><div className="ds-stack"><div className="ds-row"><Badge>Sin estado</Badge><Badge tone="success">Revisada</Badge><Badge tone="warning">Pendiente</Badge><Badge tone="error">Requiere corrección</Badge><Badge tone="info">Información</Badge></div><div className="ds-row"><Badge tone="brand">Especialidad</Badge><span className="ds-tertiary ds-small">El único badge que sigue el acento.</span></div></div></Card></div><p className="ds-demo-feedback ds-small" role="status" aria-live="polite">{message || 'Las acciones de esta página son demostraciones.'}</p></section>
        <section id="activity" className="ds-stack" aria-labelledby="activity-title"><div className="ds-section-title"><span>04</span><h2 id="activity-title" className="ds-h2">Actividad reciente</h2></div><Card title="Lo último de tu jornada" description="Eventos de muestra · 16 de septiembre de 2026"><ul className="ds-activity-list"><ActivityItem type="class" text="Clase registrada" detail="Segundo curso · Contenido y asistencia completos" dateTime="2026-09-16T09:20:00-03:00" timestamp="09:20" href="#cards" /><ActivityItem type="grades" text="Planilla actualizada" detail="Primera etapa · Calificaciones guardadas" dateTime="2026-09-16T08:45:00-03:00" timestamp="08:45" /><ActivityItem type="review" text="Revisión completada" detail="La solicitud ya tiene una conclusión" dateTime="2026-09-16T08:10:00-03:00" timestamp="08:10" /><ActivityItem type="profile" text="Perfil actualizado" detail="Datos de contacto del docente" dateTime="2026-09-16T07:35:00-03:00" timestamp="07:35" /></ul></Card></section>
        <section id="states" className="ds-stack" aria-labelledby="states-title"><div className="ds-section-title"><span>05</span><h2 id="states-title" className="ds-h2">Sin datos y carga</h2></div><div className="ds-demo-grid"><Card title="Estado vacío"><EmptyState title="Todavía no hay planillas" description="Cuando registres tu primera planilla, aparecerá aquí junto con su estado." action={<Button variant="secondary" aria-label="Crear planilla de ejemplo" icon={<Icon name="plus" />} onClick={() => notice('Crear planilla: acción de muestra.')}>Crear planilla</Button>} /></Card><Card title="Cargando la sección" description="Un skeleton conserva la estructura mientras llegan los datos"><Skeleton label="Cargando actividad de ejemplo…" lines={5} /></Card></div></section>
        <section id="profile-example" className="ds-stack" aria-labelledby="foundations-title"><div className="ds-section-title"><span>06</span><h2 id="foundations-title" className="ds-h2">Fundamentos</h2></div><div className="ds-demo-grid"><Card title="Tipografía"><div className="ds-stack"><p className="ds-h1">Título principal · 32</p><p className="ds-h2">Título de sección · 24</p><p className="ds-h3">Título de tarjeta · 20</p><p>Cuerpo de texto · 16 / 1.6</p><p className="ds-small ds-secondary">Texto secundario · 14 / 1.6</p><p className="ds-caption ds-tertiary">Caption y metadatos · 12 / 1.6</p></div></Card><Card title="Espaciado" description="Escala de 4 px; 8 px como ritmo principal"><div className="ds-space-samples">{([1,2,3,4,6,8,12] as const).map((step) => <div key={step}><span>{step * 4} px</span><i style={{ width: tokens.space[step] }} /></div>)}</div></Card></div><Card title="Paleta y niveles de texto" description="Los textos primario, secundario y terciario conservan AA en las tres superficies."><div className="ds-swatches">{Object.entries(tokens.color).filter(([key]) => ['background','surface1','surface2','surface3','text','secondary','tertiary','success','warning','error','info'].includes(key)).map(([key,value]) => <div key={key}><i style={{ background: value }} /><strong className="ds-small">{key}</strong><span className="ds-tertiary ds-caption">{value}</span></div>)}</div></Card></section>
      </main>
      <footer className="ds-gallery-footer ds-tertiary ds-small">SCA / Biblioteca base · Datos ficticios para revisión visual · Sin cambios en las pantallas existentes</footer>
    </div>
  </DesignSystem>;
}
